config/routes.rb
Creatersguild::Application.routes.draw do

  get "ideas/index"

  get "ideas/create"

  root :to => 'works#index'
  match "/top" => "works#index"

  resources :users do
    member {get "addequipment"}
  end
  resources :tools
  resources :knowledges
  resources :ideas
  resources :works do
    collection {get "searchwork"}
    member do
      put "wildwork"
      put "add_want_point"
    end
    resources :workstages,  :only => ["create","show", "new", "update", "edit"] do
      member do
        get "selectitem"
        get "afterimage"
      end
      resources :comments, :only => ["create", "index"]
      resources :points, :only => ["create", "index"]
    end
    resources :workmaterials
  end
  resources :session










end

app/models/tool.rb
class Tool < ActiveRecord::Base
  attr_accessible :product_url, :section, :title, :category, :tool_image, :tool_image_attributes
  #mount_uploader :tool_img, ToolImgUploader
  has_many :toolstagerelations
  has_many :workstages, :through => :toolstagerelations
  has_many :usertoolrelations
  has_many :users, :through => :usertoolrelations

  has_one :tool_image, :class_name => "Image::ToolImage", :as => :parent
  accepts_nested_attributes_for :tool_image

  validates :title, :presence => true, :uniqueness => true
  
  # workstagesメソッドをオーバーライド。
  # ハッシュ形式で引数に
  # :work => 「Specific Work」
  # と与えることで特定のworkに関連したworkstagesを取得可能に。
  def workstages(args = {})
    work = args[:work] || nil
    if not work
      return super
    else
      workstage_ids = work.workstage_ids & self.workstage_ids
      return Workstage.joins(:toolstagerelations).where("workstage_id IN (?)", workstage_ids).all
    end
  end
end

app/controllers/tools_controller.rb
#coding: utf-8
class ToolsController < ApplicationController

	def index
	end

	def show
		@tool = Tool.find(params[:id])
		@redirectURL = params[:redirectURL] if params[:redirectURL]
		respond_to do |format|
			format.html # show.html.erb
		end
	end

	def new
		@tool = Tool.new
		respond_to do |format|
			format.html # new.html.erb
			format.xml {render :xml => @book}
		end
	end

	def create
		@tool = Tool.new(params[:tool])
		@redirectURL = params[:redirectURL]
		if @tool.save
			@usrtoolrelation = Usertoolrelation.new(:user_id => current_user.id, :tool_id => @tool.id)
			if @usrtoolrelation.save
				redirect_to(request.referer, notice: "ツール登録が完了しました", redirectURL: @redirectURL )
			else
				redirect_to(request.referer, notice: "ツール・ユーザの紐付けに失敗しました", redirectURL: @redirectURL  )
			end
		else
			redirect_to(request.referer, notice: "ツール登録に失敗しました", redirectURL: @redirectURL  )
		end
	end

	def edit
		@tool = Tool.find(params[:id])
		respond_to do |format|
			format.html # edit.html.erb
		end
	end

	def update
		@tool = Tool.find(params[:id])
		respond_to do |format|
			if @tool.update_attributes(params[:tool])
				format.html {redirect_to(tool_path, notice: "ツール情報を修正しました" )}
				format.xml {head :ok}
			else
				format.html {render action: edit}
				format.xml {render xml: @tool.errors, status: :unprocessable_entry}
			end
		end
	end

	def destroy
		Tool.destroy(params[:id])
		respond_to do |format|
			format.html {redirect_to(controller: 'users', id: current_user.id, action: 'addequipment', notice: "ツール情報を削除しました")}
			format.xml {head :ok}
		end
	end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/edit.html.erb
<!-- Tools#edit -->
<!-- h1はapplication.cssで非表示にしてある -->
<h1 class="hidden_space">ツール　修正</h1>
<!-- Find me in app/views/tools/edit.html.erb -->

<!-- SEO対策としてタイトルを設定 -->
<% content_for :head do %>
	<% if @tool.title %>
		<title>制作日記 <%= @tool.title %> ツール 修正</title>
	<% else %>
		制作日記　ツール　修正
	<% end %>
<% end %>

ツール情報修正フォーム
<%= form_for (@tool) do |f| %>
	<div id = "tool">
		<%= f.label "：種類", :class  => 'before' %>
		<%= @tool.section %>
		<%= f.select :section, [["ハードウエア", "hare_ware"], ["ソフトウエア", "soft_ware"]] %><br>
		<%= f.label "ツールカテゴリ：", :class  => 'before' %>
		<%= @tool.category %>
		<%= f.select :category, [["未選択", "None"],:disable => true, :class => 'after'] %><br>
		<%= f.label "ツール名称：", :class  => 'before' %>
		<%= @tool.title %>
		<%= f.text_field :title, :class => 'after' %><br>
		<%= f.label "ショップリンク：", :class  => 'before' %>
		<%= @tool.product_url %>
		<%= f.text_field :product_url, :class  => 'after' %><br>
		<%= f.label "ツール画像：", :class => 'before' %><br>
		<%= @tool.tool_img %><br>
		<%= f.file_field :tool_image do |g| %><br>
			<%= g.file_field :image %><br>
    		<%= g.hidden_field :image_cache %>
		<% end %>
		<%= f.submit %>
	</div>
<% end %>

app/views/tools/new.html.erb
<h1>Tools#new</h1>
<p>Find me in app/views/tools/new.html.erb</p>

app/views/tools/show.html.erb
<!-- Tools#show -->
<!-- h1はapplication.cssで非表示にしてある -->
<h1 class="hidden_space">ツール　表示</H1>
<!-- Find me in app/views/tools/new.html.erb -->

<!-- SEO対策としてタイトルを設定 -->
<% content_for :head do %>
	<% if @tool.title %>
		<title>制作日記 <%= @tool.title %> ツール 表示</title>
	<% else %>
		制作日記　ツール　表示
	<% end %>
<% end %>

ツール情報表示フォーム
<%= form_for (@tool) do |f| %>
	<div id = "tool">
		<%= f.label "：種類" %>
		<%= @tool.section %><br>
		<%= f.label "ツールカテゴリ：" %>
		<%= @tool.category %><br>
		<%= f.label "ツール名称：" %>
		<%= @tool.title %><br>
		<%= f.label "ショップリンク：" %>
		<%= @tool.product_url %><br>
		<%= f.label "ツール画像" %>
		<%= image_tag(@tool.tool_image.image_url) if @tool.tool_image %>
		<%= hidden_field_tag :addEQURL ,@addEQURL %>
		<%= hidden_field_tag :redirectURL, @redirectURL %>
	</div>
<% end %>
<br><br>
<%= button_to("ツール情報修正", edit_tool_path, method: :get) %>
<%= button_to("ツール情報削除", tool_path, :method => :delete, :confirm => "削除してよろしいですか？") %><br>
<%= link_to("TOPページへ戻る", "/") %>