config/routes.rb
Creatersguild::Application.routes.draw do

  get "ideas/index"

  get "ideas/create"

  root :to => 'works#index'
  match "/top" => "works#index"

  resources :users do
    member {get "addequipment"}
  end
  resources :tools
  resources :knowledges
  resources :ideas
  resources :works do
    collection {get "searchwork"}
    member do
      put "wildwork"
      put "add_want_point"
    end
    resources :workstages,  :only => ["create","show", "new", "update", "edit"] do
      member do
        get "selectitem"
        get "afterimage"
      end
      resources :comments, :only => ["create", "index"]
      resources :points, :only => ["create", "index"]
    end
    resources :workmaterials
  end
  resources :session










end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :cpoint, :creaters_url, :usericon, :usericon_attributes, :pr_msg,:password,:password_confirmation, :redirectURL
  #mount_uploader :icon_img, IconImgUploader
  has_secure_password
  has_many :works
  has_many :comments
  has_many :userknowledgerelations
  has_many :knowledges, :through => :userknowledgerelations
  has_many :usertoolrelations
  has_many :tools, :through => :usertoolrelations

  has_one :usericon, :class_name => "Image::Usericon", :as => :parent
  accepts_nested_attributes_for :usericon

  validates :name, :presence => true, :uniqueness => true
  validates :password, :presence => true
  validates :email, :presence => true, :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :title, :work_pr, :start_date, :work_point, :want_point, :good_point, :status, :category_id, :user_id, :idea_id
  attr_accessor :idea_id 
  belongs_to :user
  belongs_to :category
  has_many :workmaterials
  has_many :workstages
  has_many :worktags
  has_many :idea_work_relations
  validates :title, :presence => true
  validates :work_pr, :presence => true
  validates :category, :presence => true

  def self.search(search)
  	@result = Work.where(['title like ? or category like ?', "%#{search}%", "%#{search}%"]).all
  	return @result
  end

  def self.setcat(newcat)
      #入力されたものが既存のカテゴリであった場合
      if catfound = Category.find_by_category_name(newcat)
        #見つかったカテゴリのidをcategory_idに挿入
        category_id = catfound.id
      #入力されたものが新しいカテゴリであった場合
      else
        @newcat = Category.new(:category_name => newcat)
        @newcat.save
        #新しく登録したカテゴリのidをcategory_idに挿入
        category_id = @newcat.id
      end
      return category_id
  end
  
  def tools
    Tool.joins(:toolstagerelations).where("workstage_id IN (?)", self.workstage_ids).uniq.all
  end

  def knowledges
    Knowledge.joins(:knowledgestagerelations).where("workstage_id IN (?)", self.workstage_ids).uniq.all
  end

end

app/models/workstage.rb
class Workstage < ActiveRecord::Base
  attr_accessible :workmaterial_ids, :knowledge_ids, :tool_ids, :work_id, :stage_num, :stage_pr, :stage_title, :start_image, :start_image_attributes, :after_image, :after_image_attributes
  belongs_to :work
  has_many :points
  has_many :comments, :as => :commentable
  has_many :knowledgestagerelations
  has_many :materialstagerelations
  has_many :toolstagerelations
  has_many :knowledges, :through => :knowledgestagerelations
  has_many :workmaterials, :through => :materialstagerelations
  has_many :tools, :through => :toolstagerelations
  
  has_one :start_image, :class_name => 'Image::StartImage', :as => :parent
  accepts_nested_attributes_for :start_image
  
  has_one :after_image, :class_name => 'Image::AfterImage', :as => :parent
  accepts_nested_attributes_for :after_image

  validates_presence_of :stage_title, :message => "please enter the title!"
  validates_presence_of :start_image, :message => "please set a image!"
  validates_presence_of :stage_pr, :message => "please comment something!"
end

app/controllers/workstages_controller.rb
#coding: utf-8
class WorkstagesController < ApplicationController
	def show
		@work = Work.find(params[:work_id])
		@stage = Workstage.find(params[:id])
    	@comment = Comment.new(:commentable_id => params[:id], :commentable_type => "Workstage")
		@point = Point.new(:workstage_id => params[:id])
		@comments, @has_next = Comment.get_relative(params)
		respond_to do |format|
			format.html
		end
	end

	def new
	  @work = Work.find(params[:work_id])
	  @workstage = Workstage.new(:work_id => params[:work_id], :start_image => Image::StartImage.new())
    render
    #render json: @workstage.work
	end

	def create
		@workstage = Workstage.new(params[:workstage])
		@work = Work.find(params[:work_id])
		if params[:workstage][:stage_num] == "finished"
			@work.update_attribute(:status ,"finished")
		else
			@work.update_attribute(:status, "making")
		end
		@workstage.stage_num = @work.workstages.length + 1
		#トリミング
		#保存前に1280,960にリサイズ
		if @workstage.save
			respond_to do |format|
				format.html {redirect_to [:selectitem,@work,@workstage], notice: "新規作品登録に成功しました。"}
			end
		else
			respond_to do |format|
				format.html {render "new"}
			end
		end
	end

	#工程終了画像登録ページ
	def afterimage
		@workstage = Workstage.find(params[:id])
		@work = Work.find(params[:work_id])
		@workstage.build_after_image
		render "afterimage"
	end

	#材料・ツール・文献選択画面
	def selectitem
		@workstage = Workstage.find(params[:id])
		@work = Work.find(params[:work_id])
		render "selectitem"
	end

	def edit
		@work = Work.find(params[:work_id])
		@workstage = Workstage.find(params[:id])
		render "edit"
	end

	def update
	  	@workstage = Workstage.find(params[:id])
	  	@workstage.update_attributes params[:workstage]
    	@work = Work.find(params[:work_id])
    	if params[:redirectURL]
    		@redirectURL = params[:redirectURL]
    		redirect_to[@work, @workstage, redirectURL: @redirectURL]
    	else
	  		redirect_to [@work, @workstage]
	  	end
	end

	def edit
		@work = Work.find(params[:work_id])
		@workstage = Workstage.find(params[:id])
		respond_to do |format|
			format.html # edit.html.erb
		end
	end
	
	def destroy

	end
end

app/helpers/workstages_helper.rb
module WorkstagesHelper
end

app/views/workstages/_stage_form.html.erb
<% if @workstage.errors %>
	<% @workstage.errors.each do |attribute, message| %>
		<% if message.is_a?(String) %>
			<% if attribute == :"start_image.image" %>
				<span style="color:red"><%= "The image "%></span>
			<% end %>
			<span style="color:red"><%= message %></span><br>
		<% end %>
	<% end %>
<% end %>
<%= form_for([@work,@workstage]) do |f| %>
  <%= f.label "工程のタイトル：" %><br>
  <%= f.text_field :stage_title %><br>
	<%= f.label "工程画像："%><br>
  <div id="preview"></div>
  <a href="javascript:void(0)" id="start_trim_edit_button">トリム位置を編集</a>
  <%= f.fields_for :start_image do |g| %>
    <%= g.file_field :image %><br>
    <%= g.hidden_field :image_cache %>
  <% end %>
	<%= f.label "今の状況を説明して下さい：" %><br>
	<%= f.text_area :stage_pr %><br>
	<!-- 無理矢理stage_numに完了データを運ばせている
	もっといい方法があれば是非編集して欲しい -->
	最終工程ならチェックー＞<%= f.check_box :stage_num, {},"finished", "" %><br>
	<%= f.hidden_field :work_id %>
	<%= f.submit "create stage" %>
<% end %>

app/views/workstages/_stage_form_edit.html.erb
<% if @workstage.errors %>
	<% @workstage.errors.each do |attribute, message| %>
		<% if message.is_a?(String) %>
			<span style="color:red"><%= message %></span><br>
		<% end %>
	<% end %>
<% end %>
<%= form_for([@work,@workstage]) do |f| %>
  <%= f.label "工程のタイトル：" %><br>
  <%= f.text_field :stage_title %><br>
	<%= f.label "工程画像："%><br>
  <div id="trimmer"></div>
  <%= image_tag @workstage.start_image.image_url, :size => "120x90" if @workstage.start_image %>
  <%= f.fields_for :start_image do |g| %>
    <%= g.hidden_field :image %><br>
    <%= g.hidden_field :image_cache %>
  <% end %>
	<%= f.label "今の状況を説明して下さい：" %><br>
	<%= f.text_area :stage_pr %><br>
	<%= f.hidden_field :work_id %>
	<%= f.hidden_field :stage_num %>
	<%= f.submit "create stage" %>
<% end %>

app/views/workstages/afterimage.html.erb
# coding: utf-8
<% if @workstage.errors %>
	<% @workstage.errors.each do |attribute, message| %>
		<% if message.is_a?(String) %>
			<span style="color:red"><%= message %></span><br>
		<% end %>
	<% end %>
<% end %>
<%= form_for([@work,@workstage],:url => {:action => 'update', :method => 'post'}) do |f| %>
  <%= f.label "工程終了画像：" %><br>
  <div id="trimmer"></div>
  <%= f.fields_for :after_image do |g| %>
    <%= g.file_field :image %><br>
    <%= g.hidden_field :image_cache %>
  <% end %>
	<%= f.submit "register afterimage" %>
<% end %>

app/views/workstages/edit.html.erb
<!-- h1はapplication.cssで非表示にしてある -->
<h1 class="hidden_space">作品工程　修正</h1>

<!-- SEO対策としてタイトルを設定 -->
<% content_for :head do %>
  <% if @workstage.stage_title %>
    <title>制作日記 <%= @workstage.stage_title %> 作品工程 修正</title>
  <% end %>
<% end %>

<%= render :partial => "stage_form_edit" %> 

<%= form_for([@work,@workstage],:url => {:action => 'update'}) do |f| %>
    ツール：<br>
  <% if current_user.tools %>
    <% current_user.tools.each do |tool| %>
      <%= f.check_box :tool_ids, { :checked => @workstage.tools.include?(tool), :name => 'workstage[tool_ids][]' }, tool.id, "" %><%= tool.title %><br>
    <% end %>
  <% end %>
    参考文献：<br>
  <% if current_user.knowledges %>
    <% current_user.knowledges.each do |knowledge| %>
      <%= f.check_box :knowledge_ids, { :checked => @workstage.knowledges.include?(knowledge), :name => 'workstage[knowledge_ids][]' }, knowledge.id, "" %><%= knowledge.title %><br>
    <% end %>
  <% end %>
    材料：<br>
  <% if @work.workmaterials %>
    <% @work.workmaterials.each do |workmaterial| %>
      <%= f.check_box :workmaterial_ids, { :checked => @workstage.workmaterials.include?(workmaterial), :name => 'workstage[workmaterial_ids][]' }, workmaterial.id, "" %><%= workmaterial.material %><br>
    <% end %>
  <% end %>
  <%= f.submit "登録" %>
<% end %>

<%= link_to "材料登録ページへ", controller: 'workmaterials', work_id: @work.id, action: 'new', redirectURL: "/works/"+"#{@work.id}"+"/workstages/"+"#{@workstage.id}"+"/edit" %><br>
<%= link_to "ツール・文献登録ページへ", controller: "users", id: @work.user.id, action: "addequipment", redirectURL: "/works/"+"#{@work.id}"+"/workstages/"+"#{@workstage.id}"+"/edit" %><br>

app/views/workstages/new.html.erb
<div id="ws_new_bg">
<!-- h1はapplication.cssで非表示にしてある -->
<h1>作品工程　登録</h1>

<!-- SEO対策としてタイトルを設定 -->
<% content_for :head do %>
  制作日記　作品工程　登録
<% end %>

<%= render :partial => "stage_form" %> 

<div id="popup_wrap" style="display:none;">
  <div id="popup">
    <div id="trimmer_wrap">
      <div id="trimmer"></div>
      <a href="javascript:void(0);" id="trim_edit_cancel">Cancel</a>
      <a href="javascript:void(0);" id="trim_edit_finish">OK</a>
    </div>
  </div>
</div>

<%= link_to "材料登録ページへ", controller: 'workmaterials', work_id: @work.id, action: 'new', redirectURL: "/works/"+"#{@work.id}"+"/workstages/new" %><br>
<%= link_to "ツール・文献登録ページへ", controller: "users", id: @work.user.id, action: "addequipment",  redirectURL: "/works/"+"#{@work.id}"+"/workstages/new" %><br>
</div>

app/views/workstages/selectitem.html.erb
登録済みアイテム：<br>
<% if @workstage.tools %>
	<% @workstage.tools.each do |tool|%>
		<%= tool.title %><br>
	<% end %>
<% end %>
<% if @workstage.knowledges %>
	<% @workstage.knowledges.each do |knowledge|%>
		<%= knowledge.title %><br>
	<% end %>
<% end %>
<% if @workstage.workmaterials %>
	<% @workstage.workmaterials.each do |material|%>
		<%= material.material %><br>
	<% end %>
<% end %>

<%= form_for([@work,@workstage],:url => {:action => 'update'}) do |f| %>
    ツール：<br>
  <% if current_user.tools %>
    <% current_user.tools.each do |tool| %>
      <%= f.check_box :tool_ids, { :checked => @workstage.tools.include?(tool), :name => 'workstage[tool_ids][]' }, tool.id, "" %><%= tool.title %><br>
    <% end %>
  <% end %>
    参考文献：<br>
  <% if current_user.knowledges %>
    <% current_user.knowledges.each do |knowledge| %>
      <%= f.check_box :knowledge_ids, { :checked => @workstage.knowledges.include?(knowledge), :name => 'workstage[knowledge_ids][]' }, knowledge.id, "" %><%= knowledge.title %><br>
    <% end %>
  <% end %>
    材料：<br>
  <% if @work.workmaterials %>
    <% @work.workmaterials.each do |workmaterial| %>
      <%= f.check_box :workmaterial_ids, { :checked => @workstage.workmaterials.include?(workmaterial), :name => 'workstage[workmaterial_ids][]' }, workmaterial.id, "" %><%= workmaterial.material %><br>
    <% end %>
  <% end %>
  <%= f.submit "登録" %>
<% end %>

app/views/workstages/show.html.erb
<!-- h1はapplication.cssで非表示にしてある -->
<h1 class="hidden_space">作品工程　表示</h1>

<!-- SEO対策としてタイトルを設定 -->
<% content_for :head do %>
  <% if @stage.stage_title %>
    <title>制作日記 <%= @stage.stage_title %> 作品工程 表示</title>
  <% else %>
    制作日記　作品工程　表示
  <% end %>
<% end %>

<div id="title_box" class="padding_both_side">
  <%= image_tag "border_h_fill_bottom/" + sprintf('%02d', rand(20) + 1) + ".png", :class => "border bottom" %>
  <div id="category">
    <span class="smallword">stage <%= @stage.stage_num %></span>
  </div>
  <div id="title" class="ellipsis">
    <%= @stage.stage_title if @stage.stage_title? %>
  </div>
  <!-- ページ説明 -->
  <div id="stamps">
    <%= image_tag "stamps/stamp_ws.png", :size => "80x80"%>
  </div>
</div>
<div class="user_icon_sets above_bordered">
  <div class="left_column">
    <%= render(:partial => 'shared/user_icon/small', :locals => {:user => @work.user}) %>
  </div>

  <div class="right_column">
    <div class="user_name_box">
      <%= link_to @work.user.name, @work.user %>
    </div>
    <p id="pr" class="ellipsis multiline expandable" onclick=""><!--
      --><%= @stage.stage_pr %><!--
    --></p>
    <hr class="hand_drawing">
    <div id="date">
      <span class="smallword">Since: <%= @work.created_at.strftime('%y-%m-%d %H:%M') %></span>
    </div>
  </div>
</div>
<!-- 欲しいボタン -->
<div id="want_button_wrapper2"><!-- 内容物を右寄せするための箱 -->
<div id="want_button_wrapper">
  <%= link_to "欲しい", {:controller=>"works",:action=>"add_want_point",:id=>@stage.work.id},:method => "PUT",:remote=>true , :class=>"want_button", :html => {:'data-type' => 'json'} %>
  <div id="want_point"><%= @stage.work.want_point ||= 0 %></div>
</div>
</div>
<div class="padding_both_side">
  <div id="view" class="bordered_box <%= serial_string(prefix: "type_", from: 1, to: 8, digit: 2) %>">
  	<div id="img_box">
  		<%= image_tag @stage.start_image.image_url if @stage.start_image %>
  	</div>
  </div>
</div>
<div class="above_bordered">
  <% if current_user %>
    <% if current_user.id == @work.user_id.to_i %>
      <%= button_to "工程情報修正", {:action => "edit"}, :method => :get %>
      <%= button_to "工程終了画像登録", { :action => "afterimage" }, :method => :get %>
    <% end %>
  <% end %>
</div>

<h1 id="comments_title" class="band_h padding_both_side">コメント</h1>

<%= link_to "コメント全件表示", "javascript:void(0);", :'id' => 'all_comments'%>

<div id="commentform" class="padding_both_side">
  <%= form_for [@work,@stage,@comment], :html => {:'data-type' => 'json'}, :remote => true do |f| %>
  <%= f.label "コメント入力フォーム"%><br>
  <!--
  <%= f.radio_button :comment_status,"regular",{:checked => true}%>
  <%= f.label :regular, "通常"%>
  <%= f.radio_button :comment_status,"question",{:checked => false}%>
  <%= f.label :question, "質問"%>
  <%= f.radio_button :comment_status,"suggestion",{:checked => false}%>
  <%= f.label :suggestion, "提案"%>
  -->
  <div class="inputs_wrap">
    <div>
      <div class="icon comment_status_base <%= serial_string(prefix: "type_", from: 1, to: 10, digit: 2) %>" select="regular">
        <%= f.select :comment_status, {"通常" => "regular", "質問" => "question", "提案" => "suggestion"}, {}, {:onchange => "$(this).parent().attr('select',$(this).children('option:selected').val());"} %>
      </div>
    </div>
    <div class="comment_comment_base">
      <%= f.text_area :comment, :size => "40*6", :maxlength => "140", :placeholder => "コメントを入力してください" %>
    </div>
  </div>
  <div class="button_wrap">
    <%= link_to_function "Post!", "$('#new_comment').submit()", {:class => "common_button flex_width"} %>
  </div>
  <% end %>
</div>

<div id="comments"><!-- id変更不可 -->
	<%= render(:partial => 'shared/comment', :collection => @comments) %>
</div>
<div id="more_button_box">
<%= link_to image_tag("plus.png") + 'Show More!', "javascript:void(0);", :'id' => 'more_button', :class => "common_button half_width large_font above_bordered"%>
</div>
<div class="padding_both_side">
  <span class="after_image bordered_image <%= serial_string(prefix: "type_", from: 1, to: 8, digit: 2) %>">
    <%= image_tag @stage.after_image.image_url if @stage.after_image %>
  </span>
</div>
<h1 class="band_h padding_both_side above_bordered">
  使用アイテム
</h1>
<% if @stage.workmaterials %>
  <ul class="item_list">
    <li class="headline">材料</li>
    <% @stage.workmaterials.each do |wkm| %>
      <li>
        <div class="text_left"><%= link_to (wkm.material), controller: 'workmaterials', work_id: @work.id, action: 'show', id: wkm.id, redirectURL: "/works/"+"#{@work.id}" if wkm.material? %></div>
        <div class="text_right"><%= wkm.amount if wkm.amount? %></div>
        <div class="clear"></div>
      </li>
    <% end %>
  </ul>
<% end %>
<% if @stage.tools %>
  <ul class="item_list">
    <li class="headline">道具</li>
    <% @stage.tools.each do |tool| %>
      <li>
        <div class="text_left"><%= link_to (tool.title), controller: 'tools', action: 'show', id: tool.id %></div>
        <div class="clear"></div>
      </li>
    <% end %>
  </ul>
<% end %>
<% if @stage.knowledges %>
  <ul class="item_list">
    <li class="headline">参考文献</li>
    <% @stage.knowledges.each do |knowledge| %>
      <li>
        <div class="text_left"><%= link_to (knowledge.title), controller: 'knowledges', action: 'show', id: knowledge.id %></div>
        <div class="clear"></div>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to "TOPに戻る", :root %>
<%= link_to "作品に戻る", work_path(@stage.work_id) %>

<!-- javascriptから初期ロード時に取得したコメントを参照するために必須 -->
<script type="text/javascript">
	comments = new Comments(<%== @comments.to_json %>);
	comments.has_next = <%== @has_next %>;
	
	points = <%== @stage.points.to_json %>;
</script>

<div id="popup_wrap" style="display:none;">
  <div id="popup">
    <div id="commentFormWithPoint" class="new_comment">
      <p class="above_bordered">コメント入力フォーム</p>
      <div class="image_wrap bordered_box <%= serial_string(prefix: "type_", from: 1, to: 8, digit: 2) %>">
        <div class="content">
          <%= image_tag @stage.start_image.image_url if @stage.start_image %>
          <div class="marker invert">
          </div>
        </div>
      </div>
      <div class="inputs_wrap above_bordered">
        <div class="icon comment_status_base <%= serial_string(prefix: "type_", from: 1, to: 10, digit: 2) %>" select="regular">
          <select onchange="$(this).parent().attr('select',$(this).children('option:selected').val());">
            <option value="regular">通常</option>
            <option value="question">質問</option>
            <option value="suggestion">提案</option>
          </select>
        </div>
        <div class="comment_comment_base">
          <textarea placeholder="コメントを入力してください"></textarea>
        </div>
      </div>
      <div class="button_wrap">
        <input type="button" value="コメントを投稿する" id="cppost">
        <input type="button" value="キャンセル" id="cpcancel">
      </div>
    </div>
  </div>
</div>
